### ISSUE TITLE
[ENHANCEMENT] - Add Support for Multiple Authentication

### ISSUE THREAD

**Issue by asadali214** [apimatic/go-core-runtime#48]
```[tasklist]
### Tasks
- [x] Add the public user-facing changes for multiple auth in CallBuilder's `Authenticate` function
- [x] Add support for combining authentication credentials as AND/OR groups
- [x] Add unit tests to cover this feature
- [x] Make sure all unit tests pass
```
