### ISSUE TITLE
Add support for error handling with dynamic and static messages

### ISSUE THREAD

**Issue by asadali214** [apimatic/go-core-runtime#52]
```[tasklist]
### Tasks
- [x] Add the interface changes to collect ErrorBuilders as a map
- [x] Add the capability of returning API errors within CallBuilder
- [x] Add a JSON pointer dependency to cater to the dynamic error messaging
- [x] Add unit tests to cover the newly added logical changes and make them all pass
```
